[workspace]
members = [
    "array-box",
    "geometry-box",
    "reference-box",
    "string-box",
    "value-box",
    "value-box-extensions"
]
resolver = "2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3